id: kiali-test-service
kind: Template
apiVersion: v1
name: Kiali Test Application
description: Deploys replicasets for the test mesh
metadata:
  name: kiali-test-service
  labels:
    kiali-test: test-service
parameters:
- name: SERVICE_NAME
  description: The name to use for the service
  required: true
- name: SERVICE_VERSION
  description: The version of the deployment
  value: v1
- name: IMAGE_NAME
  description: The name to use for the image
  value: kiali/kiali-test-service
- name: IMAGE_VERSION
  description: The name to use for the image version
  value: latest
objects:
- kind: ReplicaSet
  apiVersion: extensions/v1beta1
  metadata:
    name: kiali-test-service-${SERVICE_NAME}-${SERVICE_VERSION}
  spec:
    replicas: 1
    selector:
      matchLabels:
        kiali: test-service-${SERVICE_NAME}-${SERVICE_VERSION}
    template:
      metadata:
        labels:
          kiali: test-service-${SERVICE_NAME}-${SERVICE_VERSION}
          app: ${SERVICE_NAME}
      spec:
        containers:
          - name: kiali-test-service-${SERVICE_NAME}-${SERVICE_VERSION}
            image: ${IMAGE_NAME}:${IMAGE_VERSION}
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 8888
