apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb-v1
  namespace: {{ bookinfo.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
        version: v1
    spec:
      containers:
      - name: mongodb
        image: istio/examples-bookinfo-mongodb:{{ bookinfo.version }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017