apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v2-mongodb
  namespace: {{ bookinfo.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v2-mongodb
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: ratings
        version: v2-mongodb
    spec:
      containers:
      - name: ratings
        image: {{ bookinfo.hub }}/examples-bookinfo-ratings-v2:{{ bookinfo.version }}
        imagePullPolicy: IfNotPresent
        env:
          - name: MONGO_DB_URL
            value: mongodb://mongodb:27017/test
        ports:
        - containerPort: 9080
