  - name: Set Breadth Sink Route
    vars:
      fqdn_services_breadth_sink_route: "{{all_services | map(attribute='fqdn') | select('search', 'kiali-test-breadth-sink') | list}}"
    set_fact:
      route: "http://{{fqdn_services_breadth_sink_route[0]}}/route?path={{item}},{{fqdn_services_breadth_sink_route[-1]}};{{kiali_test_breadth_sink_route}}"
      namespace: "{{all_services | map(attribute='namespace') | select('search', 'kiali-test-breadth-sink') | list | first }}"
    with_items:
      - "{{ fqdn_services_breadth_sink_route | reverse | list }} "