  - name: Set Breadth Route
    vars:
      fqdn_services_breadth_route: "{{all_services | map(attribute='fqdn') | select('search', 'kiali-test-breadth') | list | difference(all_services | map(attribute='fqdn') | select('search', 'kiali-test-breadth-sink') | list) }}"
    set_fact:
      route: "http://{{fqdn_services_breadth_route[0]}}/route?path={{item}};{{kiali_test_breadth_route}}"
      kiali_test_breadth_namespace: "{{all_services | map(attribute='namespace') | select('search', 'kiali-test-breadth') | list | first }}"
    with_items:
      - "{{ fqdn_services_breadth_route | reverse | list  }}"