  - name: Set Depth route
    vars:
      fqdn_services_depth: "{{all_services | map(attribute='fqdn') | select('search', 'kiali-test-depth') | list | difference(all_services | map(attribute='fqdn') | select('search', 'kiali-test-depth-sink') | list)}}"
    set_fact:
      route: "http://{{fqdn_services_depth[0]}}/route?path={{ fqdn_services_depth | list | join(',') }}"
      namespace: "{{all_services | map(attribute='namespace') | select('search', 'kiali-test-depth') | list | first }}"