- name: Wait until all pods of {{ item.name }} are running
  k8s:
    definition:
      apiVersion: "{{ item.api_version }}"
      kind: "{{ item.deployment_type }}"
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ item.namespace }}"
  register: status
  until: (status.result.status.ready_replicas is defined and status.result.status.replicas and status.result.status.ready_replicas == status.result.status.replicas) or
       (status.result.status.readyReplicas is defined and status.result.status.replicas and status.result.status.readyReplicas == status.result.status.replicas) 
  retries: 100
  delay: 10
