- name: Wait until all pods of {{ item.name }} are running
  k8s:
    definition:
      apiVersion: "{{ item.api_version }}"
      kind: "{{ item.deployment_type }}"
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ item.namespace }}"
  register: status
  until: (status.result.status.number_ready is defined and status.result.status.number_available is defined and status.result.status.number_ready == status.result.status.number_available ) or
        (status.result.status.numberReady is defined and status.result.status.numberAvailable is defined and status.result.status.numberReady ==  status.result.status.numberAvailable) 
  retries: 100
  delay: 10
