- name: Deleting Namespace {{ item }}
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
    state: absent
  ignore_errors: true

- name: Create Namespace {{ item }}
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
    state: present
  register: projectStatus
  until: projectStatus.changed == true
  retries: 100
  delay: 20