- name: "Deploy Traffic Generator Configmap in {{ item.namespace }}"
  k8s:
   state: present
   definition: "{{ lookup('template', 'templates/traffic-generator-configmap.yml') }}"


- name: "Deploy Traffic Generator in {{ item.namespace }} with Automatic Injection"
  k8s:
   state: present
   definition: "{{ lookup('template', 'templates/traffic-generator.yml') }}"
  when: not istio_manual_injection.enabled

- name: Inject Kubectl if manual injection is defined
  shell: "echo \"{{ lookup('template', 'templates/traffic-generator.yml') }}\" | istioctl kube-inject -f -"
  register: istio_template
  when: istio_manual_injection.enabled

- name: "Deploy Traffic Generator with manual injection"
  k8s:
    state: present
    definition: "{{ istio_template['stdout'] | regex_replace('---', '') }}"
  when: istio_manual_injection.enabled



