apiVersion: v1
kind: Service
metadata:
  name: {{ item.name }}
  namespace: {{ bookinfo.namespace }}
  labels:
    app: {{ item.app }}
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: {{ item.app }}

