kind: Deployment
apiVersion: apps/v1
metadata:
  name:  workload{{ item.0.name | regex_replace('service') }}-{{ item.1 }}
  namespace: {{ item.0.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ item.0.app }} 
      version: workload{{ item.0.name | regex_replace('service') }}-{{ item.1 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: {{ item.0.app }} 
        version:  workload{{ item.0.name | regex_replace('service') }}-{{ item.1 }}
    spec:
      containers:
        - name: workload{{ item.0.name | regex_replace('service') }}-{{ item.1 }}
          image: kiali/kiali-test-service:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8888