apiVersion: v1
kind: Service
metadata:
  name: {{ item.name }}
  namespace: {{ item.namespace }}
  labels:
    app: {{ item.app }}
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    app: {{ item.app }}