- name: Download Istio Release
  shell: "curl -L https://git.io/getLatestIstio | sh - "
  environment: 
    ISTIO_VERSION: "{{ istio_manual_injection.version }}"


- name: "Move Istioctl"
  shell: "mv istio-{{ istio_manual_injection.version }}/bin/istioctl /usr/local/bin"


- name: "Check istioctl version"
  shell: "istioctl version"