apiVersion: bookinfo.kiali.io/v1
kind: Bookinfo
metadata:
  name: bookinfo-installation
spec:
  bookinfo:
    version: 1.15.0
    namespace: ${BOOKINFO_NAMESPACE}
    hub: ${BOOKINFO_HUB}
    control_plane_namespace: ${CONTROL_PLANE_NAMESPACE}
    mongodb: true
    mysql: true
