- name: "Deleting Namespace {{ item }}"
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
    state: absent
  ignore_errors: true

- name: "Create Namespace {{ item }}"
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
    state: present
  register: projectStatus
  until: projectStatus.changed == true
  retries: 100
  delay: 20



- name: "Update SCC policy to allow {{ item }} use anyuid"
  command: "oc adm policy add-scc-to-user anyuid -z default -n {{ item }}"

- name: "Update SCC policy to allow {{ item }} use privileged"
  command: "oc adm policy add-scc-to-user privileged -z default -n {{ item }}"

