apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: preference
    version: v2
  name: preference-v2
  namespace: {{ item.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preference
      version: v2
  template:
    metadata:
      labels:
        app: preference
        version: v2
{% if not istio_manual_injection.enabled %}
      annotations:
        sidecar.istio.io/inject: "{{ item.sidecar }}"
{% endif %}
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:///dev/./urandom
        image: quay.io/rhdevelopers/istio-tutorial-preference:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 1
        name: preference
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false
