apiVersion: v1
kind: Service
metadata:
  name: preference
  namespace: {{ item.namespace }}
  labels:
    app: preference    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: preference
