apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-v1
  namespace: {{ bookinfo.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: mysqldb
        version: v1
    spec:
      containers:
      - name: mysqldb
        image: {{ bookinfo.hub }}/examples-bookinfo-mysqldb:{{ bookinfo.version }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: rootpasswd
        args: ["--default-authentication-plugin","mysql_native_password"]
