- name: Service Mesh Member
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'templates/istio/smm.yml') }}"
  ignore_errors: true  

- name: Services
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.file) }}"
  with_items:
    - { name: "Customer", namespace: '{{ meta.namespace }}', file: 'templates/customer/customer-service.yml'}
    - { name: "Preference", namespace: '{{ meta.namespace }}', file: 'templates/preference/preference-service.yml'}
    - { name: "Recommendation", namespace: '{{ meta.namespace }}', file: 'templates/recommendation/recommendation-service.yml'}

- name: Deployments
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.file) }}"
  with_items:
  - { name: 'customer-v1', namespace: '{{ meta.namespace }}', file: 'templates/customer/deployment-v1.yml'}
  - { name: 'preference-v1', namespace: '{{ meta.namespace }}', file: 'templates/preference/deployment-v1.yml'}
  - { name: 'preference-v1', namespace: '{{ meta.namespace }}', file: 'templates/preference/deployment-v2.yml'}
  - { name: 'recommendation-v1', namespace: '{{ meta.namespace }}', file: 'templates/recommendation/deployment-v1.yml'}
  - { name: 'recommendation-v2', namespace: '{{ meta.namespace }}', file: 'templates/recommendation/deployment-v2.yml'}

- name: Openshift Route
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.file) }}"
  with_items:
   - {file: 'templates/istio/customer-route.yml'}
  register: route

- name: Customer Istio Gateway
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.file) }}"
  with_items:
   - {file: 'templates/istio/customer-gateway.yml'}
   - {file: 'templates/istio/customer-vs.yml'}

- name: Tutorial Destination Rules
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.file) }}"
  with_items:
   - {file: 'templates/istio/customer-dr.yml'}
   - {file: 'templates/istio/preference-dr.yml'}
   - {file: 'templates/istio/recommendation-dr.yml'}
  
- name: Set Full Route for Traffic Generator for Present
  set_fact:
    full_route: "http://{{ route.results[0]['result']['spec']['host'] }}"
  when: state == "present"

- name: Set Full Route for Traffic Generator for Absent
  set_fact:
    full_route: ""
  when: state == "absent"

- name: Get State for Traffic Generator
  set_fact:
    state_traffic_generator: "{{ state }}"

- name: Traffic Generator
  include_role: 
    name: traffic-generator
  vars:
    namespace: "{{ meta.namespace }}"
    route: "{{ full_route }}"
    state: "{{ state_traffic_generator }}"
