- name: Create Services
  k8s:
    state: present
    definition: "{{ lookup('template', item.file) }}"
  with_items:
    - { namespace: '{{ meta.namespace }}', file: 'templates/customer/customer-service.yml'}
    - { namespace: '{{ meta.namespace }}', file: 'templates/preference/preference-service.yml'}
    - { namespace: '{{ meta.namespace }}', file: 'templates/recommendation/recommendation-service.yml'}



- name: Create the Items
  include: ../common_tasks/deploy_istio_item.yml
  with_items:
  - { name: 'customer-v1', namespace: '{{ meta.namespace }}', file: 'templates/customer/deployment-v1.yml', sidecar: true }
  - { name: 'preference-v1', namespace: '{{ meta.namespace }}', file: 'templates/preference/deployment-v1.yml', sidecar: true }
  - { name: 'preference-v1', namespace: '{{ meta.namespace }}', file: 'templates/preference/deployment-v2.yml', sidecar: true }
  - { name: 'recommendation-v1', namespace: '{{ meta.namespace }}', file: 'templates/recommendation/deployment-v1.yml', sidecar: true }
  - { name: 'recommendation-v2', namespace: '{{ meta.namespace }}', file: 'templates/recommendation/deployment-v2.yml', sidecar: true }

- name: Create Openshift Route
  k8s:
    state: present
    definition: "{{ lookup('template', item.file) }}"
  with_items:
   - {file: 'templates/istio/customer-route.yml'}
  register: route

- name: Deploy Customer Istio Gateway
  k8s:
    state: present
    definition: "{{ lookup('template', item.file) }}"
  with_items:
   - {file: 'templates/istio/customer-gateway.yml'}
   - {file: 'templates/istio/customer-vs.yml'}


- name: Deploy Tutorial Destination Rules
  k8s:
    state: present
    definition: "{{ lookup('template', item.file) }}"
  with_items:
   - {file: 'templates/istio/customer-dr.yml'}
   - {file: 'templates/istio/preference-dr.yml'}
   - {file: 'templates/istio/recommendation-dr.yml'}
  
- name: Set Full Route for Traffic Generator
  set_fact:
    full_route: "http://{{ route.results[0]['result']['spec']['host'] }}"

- name: Create the traffic generator
  include_role: 
    name: traffic-generator
  vars:
    namespace: "{{ meta.namespace }}"
    route: "{{ full_route }}"
