---
# defaults file for redhat_tutorial
redhat_tutorial:
  enabled: true
  namespace: redhat-istio-tutorial

istio_manual_injection:
  enabled: false
  version: '1.1.7'

traffic_generator:
  sidecar: false