- name: Install Istioctl
  include: ../common_tasks/install_istioctl.yml
  when: istio_manual_injection.enabled
  
- name: Create Services
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
          name: "{{ item.name }}"
          namespace: "{{ item.namespace }}"
      spec:
        selector:
          name: "{{ item.pod_name_label }}"
        ports:
        - name: http
          port: 80
          targetPort: 8888
  with_items:
   - { namespace: 'kiali-test-frontend', name: 'productpage', pod_name_label: 'productpage' }
   - { namespace: 'kiali-test-frontend', name: 'details', pod_name_label: 'details' }
   - { namespace: 'kiali-test-reviews', name: 'reviews', pod_name_label: 'reviews' }
   - { namespace: 'kiali-test-ratings', name: 'ratings', pod_name_label: 'ratings' }

- name: Create DR and Virtual Service
  k8s:
    state: present
    definition: "{{ lookup('template', item.file) }}"
  with_items:
    - { namespace: 'kiali-test-frontend', file: 'templates/complex-mesh/destinationrule-template.yml', name: 'detailsdr', host: 'details', subset_name: 'v1', subset_version: 'v1' }
    - { namespace: 'kiali-test-frontend', file: 'templates/complex-mesh/virtualservice-template.yml', name: 'detailsvs', host: 'kiali.io', destination_host: 'details', destination_subset: 'v1' }
    

- name: Create the Items
  include: ../common_tasks/deploy_istio_item.yml
  with_items:
  - { namespace: 'kiali-test-frontend', file: 'templates/complex-mesh/app-deployment.yml', name: 'productpagev1', app: 'productpage', version: 'v1', sidecar: true }
  - { namespace: 'kiali-test-frontend', file: 'templates/complex-mesh/app-replicaset.yml', name: 'detailsv1', app: 'details', version: 'v1', sidecar: true }
  - { namespace: 'kiali-test-reviews', file: 'templates/complex-mesh/app-deployment.yml', name: 'reviewsv1', app: 'reviews', version: 'v1', sidecar: true }
  - { namespace: 'kiali-test-reviews', file: 'templates/complex-mesh/app-replicaset.yml', name: 'reviewsv2', app: 'reviews', version: 'v2', sidecar: true }
  - { namespace: 'kiali-test-reviews', file: 'templates/complex-mesh/workload-deployment.yml', name: 'reviews003', project_name: 'reviews', build_number: '0.0.3', sidecar: true }
  - { namespace: 'kiali-test-ratings', file: 'templates/complex-mesh/app-deployment.yml', name: 'ratingsv1', app: 'ratings', version: 'v1', sidecar: true }
  - { namespace: 'kiali-test-ratings', file: 'templates/complex-mesh/app-deployment.yml', name: 'ratingsv2', app: 'ratings', version: 'v2', sidecar: true }
  - { namespace: 'kiali-test-ratings', file: 'templates/complex-mesh/app-deployment.yml', name: 'ratingsv3', app: 'ratings', version: 'v3', sidecar: false }
  - { namespace: 'kiali-test-ratings', file: 'templates/complex-mesh/app-replicaset.yml', name: 'ratingsv4', app: 'ratings', version: 'v4', sidecar: false }
  - { namespace: 'kiali-test-ratings', file: 'templates/complex-mesh/app-statefulset.yml', name: 'ratingsv5', app: 'ratings', version: 'v5', sidecar: true }
  - { namespace: 'kiali-test-ratings', file: 'templates/complex-mesh/app-daemonset.yml', name: 'ratingsv6', app: 'ratings', version: 'v6', sidecar: true }

- name: Create the traffic generator
  include: ../common_tasks/deploy_traffic_generator.yml
  with_items:
   - { namespace: 'kiali-test-frontend', route: 'http://productpage/route?path=details;http://productpage/route?path=reviews.kiali-test-reviews.svc.cluster.local,ratings.kiali-test-ratings.svc.cluster.local', sidecar: traffic_generator.sidecar }
