- name: Install Istioctl
  include: ../common_tasks/install_istioctl.yml
  when: istio_manual_injection.enabled

- name: Create Services
  k8s:
    state: present
    definition: "{{ lookup('template', item.file) }}"
  with_items:
    - { namespace: '{{ redhat_tutorial.namespace }}', file: 'templates/customer/customer-service.yml'}
    - { namespace: '{{ redhat_tutorial.namespace }}', file: 'templates/preference/preference-service.yml'}
    - { namespace: '{{ redhat_tutorial.namespace }}', file: 'templates/recommendation/recommendation-service.yml'}



- name: Create the Items
  include: ../common_tasks/deploy_istio_item.yml
  with_items:
  - { namespace: '{{ redhat_tutorial.namespace }}', file: 'templates/customer/deployment-v1.yml', sidecar: true }
  - { namespace: '{{ redhat_tutorial.namespace }}', file: 'templates/preference/deployment-v1.yml', sidecar: true }
  - { namespace: '{{ redhat_tutorial.namespace }}', file: 'templates/preference/deployment-v2.yml', sidecar: true }
  - { namespace: '{{ redhat_tutorial.namespace }}', file: 'templates/recommendation/deployment-v1.yml', sidecar: true }
  - { namespace: '{{ redhat_tutorial.namespace }}', file: 'templates/recommendation/deployment-v2.yml', sidecar: true }
  - { namespace: '{{ redhat_tutorial.namespace }}', file: 'templates/recommendation/deployment-v2-timeout.yml', sidecar: true }


- name: Create the traffic generator
  include: ../common_tasks/deploy_traffic_generator.yml
  with_items:
   - { namespace: '{{ redhat_tutorial.namespace }}', route: 'http://customer/', sidecar: traffic_generator.sidecar }
