apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scalemeshes.scalemesh.kiali.io
spec:
  group: scalemesh.kiali.io
  names:
    kind: ScaleMesh
    listKind: ScaleMeshList
    plural: scalemeshes
    singular: scalemesh
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
