- name: Deploy ReplicaSet {{ item.name }} without Sidecar
  shell: "oc process -f templates/app-replicaset.yml -p NAME={{ item.name }} -p APP_NAME={{ item.app }} -p APP_VERSION={{ item.version }} | oc  apply -n {{ item.namespace }} -f -"
