kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: {{ item.name }}
  namespace: {{ item.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ item.app }}
      app: {{ item.app }}
      version: {{ item.version }}
  template:
    metadata:
{% if not istio_manual_injection.enabled %}
      annotations:
        sidecar.istio.io/inject: "{{ item.sidecar }}"
{% endif %}
      labels:
        name: {{ item.app }}
        app: {{ item.app }}
        version: {{ item.version }}
    spec:
      containers:
        - name: kiali-{{ item.name }}-{{ item.version }}
          image: kiali/kiali-test-service:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8888