apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ item.name }}
  namespace: {{ item.namespace }}
spec:
  host: {{ item.destination_host }}
  subsets:
  - name: v1
    labels:
      version: v1
  
  - name: v2
    labels:
      version: v2

  - name: v3
    labels:
      build_number: 0.0.3
