apiVersion: kiali-test-mesh.kiali.io/v1
kind: Installation
metadata:
  name: kili-test-mesh-installation
spec:
  # Add fields here
  complex_mesh: true
  proxy_version: '1.1.0-snapshot.5'
  proxy_image: 'docker.io/istio/proxyv2'
  proxy_init: 'docker.io/istio/proxy_init'