  - name: Grant Permissions to each Kiali Test Meshes Projects
    shell: "oc adm policy add-scc-to-user privileged -z default -n {{item}}"
    with_items:
      - "{{ all_services | map(attribute='namespace') | list | unique }}"

  - name: Deploy Kiali Test Meshes Services
    shell: "oc process -f templates/service-template.yml -p SERVICE_NAME={{ item.name }} -p APP_NAME={{ item.app }} | istioctl kube-inject -f - | oc  apply -n {{ item.namespace }} -f -"
    with_items:
      - "{{ all_services }}"

  - name: Deploy Kiali Test Pods
    shell: "oc process -f templates/workload-template.yml -p DEPLOYMENT_TYPE={{deployment_type}} -p SERVICE_NAME={{ item.0.name }} -p WORKLOAD_NAME=workload{{ item.0.name | regex_replace('service') }} -p APP_NAME={{ item.0.app }} -p IMAGE_NAME='kiali/kiali-test-service' -p WORKLOAD_VERSION={{ item.1 }} -p IMAGE_VERSION=latest | istioctl kube-inject -f - | oc  apply -n {{ item.0.namespace }} -f -"
    with_nested:
    - "{{ all_services }}"
    - "{{ versions }}"

  - name: Wait until all pods are running
    openshift_raw:
      definition:
        apiVersion: v1
        kind: "{{ deployment_type }}"
        metadata:
          name: "kiali-workload{{ item.0.name | regex_replace('service') }}-{{ item.1 }}"
          namespace: "{{ item.0.namespace }}"
        spec:
          selector:
            matchLabels:
              app: "{{ item.0.app }}"
              version: "workload{{ item.0.name | regex_replace('service') }}-{{ item.1 }}"
    with_nested:
      - "{{ all_services }}"
      - "{{ versions }}"
    register: replicaResult
    until: (replicaResult.result.status.ready_replicas is defined and replicaResult.result.status.ready_replicas == 1) or
         (replicaResult.result.status.readyReplicas is defined and replicaResult.result.status.readyReplicas == 1)
    retries: 100
    delay: 10

  - name: Deploy Traffic Generator ConfigMaps to Kiali Namespaces
    shell: "curl https://raw.githubusercontent.com/kiali/kiali-test-mesh/master/traffic-generator/openshift/traffic-generator-configmap.yaml | DURATION='0s' ROUTE=\"{{item.route}}\" RATE='1'  envsubst | oc apply -n {{item.namespace}} -f -"
    when: "item.mesh in meshes and item.namespace != ''"
    with_items:
      - { namespace: "{{ kiali_test_depth_namespace }}", route: '{{kiali_test_depth_route}}', mesh: "kiali-test-depth" }
      - { namespace: "{{ kiali_test_breadth_namespace }}", route: '{{kiali_test_breadth_route}}', mesh: "kiali-test-breadth" }
      - { namespace: "{{ kiali_test_circle_namespace }}", route: '{{kiali_test_circle_route}}', mesh: "kiali-test-circle" }
      - { namespace: "{{ kiali_test_circle_callback_namespace }}", route: '{{kiali_test_circle_callback_route}}', mesh: "kiali-test-circle-callback" }
      - { namespace: "{{ kiali_test_hourglass_namespace }}", route: '{{kiali_test_hourglass_route}}', mesh: "kiali-test-hourglass" }
      - { namespace: "{{ kiali_test_breadth_sink_namespace }}", route: '{{kiali_test_breadth_sink_route}}', mesh: "kiali-test-breadth-sink" }
      - { namespace: "{{ kiali_test_depth_sink_namespace }}", route: '{{kiali_test_depth_sink_route}}', mesh: "kiali-test-depth-sink" }

  - name: Deploy Trafic Generator
    shell: "curl https://raw.githubusercontent.com/kiali/kiali-test-mesh/master/traffic-generator/openshift/traffic-generator.yaml | istioctl kube-inject -f - | oc apply -n {{item.namespace}} -f -"
    when: "item.mesh in meshes and item.namespace != ''"
    with_items:
      - { namespace: "{{ kiali_test_depth_namespace }}", mesh: "kiali-test-depth" }
      - { namespace: "{{ kiali_test_breadth_namespace }}", mesh: "kiali-test-breadth" }
      - { namespace: "{{ kiali_test_circle_namespace }}", mesh: "kiali-test-circle" }
      - { namespace: "{{ kiali_test_hourglass_namespace }}", mesh: "kiali-test-hourglass"}
      - { namespace: "{{ kiali_test_circle_callback_namespace }}", mesh: "kiali-test-circle-callback" }
      - { namespace: "{{ kiali_test_breadth_sink_namespace }}", mesh: "kiali-test-breadth-sink" }
      - { namespace: "{{ kiali_test_depth_sink_namespace }}", mesh: "kiali-test-depth-sink" }
