apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ratings
  namespace: {{ bookinfo.namespace }}
spec:
  host: ratings
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2-mongodb
    labels:
      version: v2-mongodb
  - name: v2-mysql
    labels:
      version: v2-mysql