apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: bookinfos.kiali-test-mesh.kiali.io
  namespace: kiali-test-mesh-operator
spec:
  group: kiali-test-mesh.kiali.io
  names:
    kind: Bookinfo
    listKind: BookinfoList
    plural: bookinfos
    singular: bookinfo
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
