apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ meta.namespace }}-gateway
  namespace: {{ meta.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
{% if state == "present" %}    
     - "{{ route.results[0]['result']['spec']['host'] }}"
{% endif %}
{% if state == "absent" %}
    - "example.com"
{% endif %}