apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ meta.namespace }}-vs
  namespace: {{ meta.namespace }}
spec:
  hosts:
{% if state == "present" %}    
  - "{{ route.results[0]['result']['spec']['host'] }}"
{% endif %}
{% if state == "absent" %}
  - "example.com"
{% endif %}
  gateways:
  - {{ meta.namespace }}-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: customer
        port:
          number: 8080
