apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-generator-config
  namespace: {{ item.namespace }}
  labels:
    kiali-test: traffic-generator-config
data:
  duration: "0s"
  route: {{ item.route }}
  rate: "1"
