- name: Create Services
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/bookinfo-service.yml') }}"
  with_items:
    - {name: 'details', app: 'details'}
    - {name: 'ratings', app: 'ratings'}
    - {name: 'reviews', app: 'reviews'}
    - {name: 'productpage', app: 'productpage'}


- name: Install Bookinfo Static Assets
  include: ../common_tasks/deploy_istio_item.yml
  with_items:
   - {name: 'details-v1', app: 'details', version: 'v1', file: 'templates/bookinfo-deployment.yml', image: "{{ bookinfo.hub }}/examples-bookinfo-details-v1", sidecar: true}
   - {name: 'ratings-v1', app: 'ratings', version: 'v1', file: 'templates/bookinfo-deployment.yml', image: "{{ bookinfo.hub }}/examples-bookinfo-ratings-v1", sidecar: true}
   - {name: 'reviews-v1', app: 'reviews', version: 'v1', file: 'templates/bookinfo-deployment.yml', image: "{{ bookinfo.hub }}/examples-bookinfo-reviews-v1", sidecar: true}
   - {name: 'reviews-v2', app: 'reviews', version: 'v2', file: 'templates/bookinfo-deployment.yml', image: "{{ bookinfo.hub }}/examples-bookinfo-reviews-v2", sidecar: true}
   - {name: 'reviews-v3', app: 'reviews', version: 'v3', file: 'templates/bookinfo-deployment.yml', image: "{{ bookinfo.hub }}/examples-bookinfo-reviews-v3", sidecar: true}
   - {name: 'productpage-v1', app: 'productpage', version: 'v1', file: 'templates/bookinfo-deployment.yml', image: "{{ bookinfo.hub }}/examples-bookinfo-productpage-v1", sidecar: true}

- name: Deploy MongoDB
  k8s:
    state: present
    definition: "{{ lookup('template', item.file) }}"
  when: bookinfo.mongodb
  with_items:
   - {file: 'templates/mongodb/service.yml'}


- name: Deploy MySQL
  k8s:
    state: present
    definition: "{{ lookup('template', item.file) }}"
  when: bookinfo.mysql
  with_items: 
   - {file: 'templates/mysql/secret.yml'}
   - {file: 'templates/mysql/service.yml'}
   


- name: Deploy Ratings V2 MongoDB
  include: ../common_tasks/deploy_istio_item.yml
  when: bookinfo.mongodb
  with_items:
    - {name: 'ratings-mongodb', file: 'templates/bookinfo-ratings-v2-mongodb.yml', sidecar: true}
    - {name: 'mongodb', file: 'templates/mongodb/deployment.yml', sidecar: true}

  
 
- name: Deploy Ratings V2 MySQL
  include: ../common_tasks/deploy_istio_item.yml
  when: bookinfo.mysql
  with_items:
    - {name: 'mysql', file: 'templates/mysql/deployment.yml', sidecar: true}
    - {name: 'ratings-mysql', file: 'templates/bookinfo-ratings-v2-mysql.yml', sidecar: true}


- name: Create Openshift Route
  k8s:
    state: present
    definition: "{{ lookup('template', item.file) }}"
  with_items:
   - {file: 'templates/istio/bookinfo-route.yml'}
  register: route

- name: Deploy Bookinfo Istio Gateway
  k8s:
    state: present
    definition: "{{ lookup('template', item.file) }}"
  with_items:
   - {file: 'templates/istio/bookinfo-gateway.yml'}
   - {file: 'templates/istio/bookinfo-vs.yml'}


- name: Deploy Bookinfo Destination Rules
  k8s:
    state: present
    definition: "{{ lookup('template', item.file) }}"
  with_items:
   - {file: 'templates/istio/bookinfo-productpage-dr.yml'}
   - {file: 'templates/istio/bookinfo-reviews-dr.yml'}
   - {file: 'templates/istio/bookinfo-ratings-dr.yml'}
   - {file: 'templates/istio/bookinfo-details-dr.yml'}  

- name: Set Full Route for Traffic Generator
  set_fact:
    full_route: "http://{{ route.results[0]['result']['spec']['host'] }}/productpage"

- name: Create the traffic generator
  include_role: 
    name: traffic-generator
  vars:
    namespace: "{{ bookinfo.namespace }}"
    route: "{{ full_route }} "